dist: xenial

language: python

python:
  - "3.7"
  - "3.8"

install:
  - sudo apt-get update
  - . ./scripts/install_miniconda.sh
  - conda info -a
  - . ./scripts/create_testenv.sh
  - pip install coveralls pytest-cov pylint

services:
  - xvfb

script:
  - ./scripts/test.sh

after_success:
  - coveralls

before_cache:
# clean unused packages & installed files from conda cache
# this makes the cache rebuilt less frequently
  - conda clean --yes --tarballs --packages --index-cache
  - rm -rf $HOME/miniconda/pkgs/cache

cache:
  directories:
    - $HOME/miniconda
