name: Run tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    name: Set up Python ${{ matrix.python-version }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge, defaults
          channel-priority: true
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true

      - name: Install Bambi and all its dependencies
        run: |
          conda install -c conda-forge python-graphviz
          conda install pip
          pip install .
          pip install .[dev]
          pip install .[jax]

      - name: Run linters
        run: |
          echo "Running black..."
          black bambi --check

          echo "Checking code style with pylint..."
          pylint bambi

      - name: Run tests
        run: python -m pytest -vv --cov=bambi --cov-report=term --cov-report=xml tests
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
